from flask import Flask, request, Response, jsonify
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import psutil
import time
from flask_cors import CORS
import gc
import grpc
import llm_pb2
import llm_pb2_grpc

app = Flask(__name__)
CORS(app, supports_credentials=True, origins=["http://localhost:5173"])

# Model setup
model_id = "mistralai/Mistral-7B-v0.1"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="cpu"
)
total_layers = len(model.model.layers)
print(f"Loaded {total_layers} layers on CPU")

print(f"Available RAM: {psutil.virtual_memory().available / 1024**3:.2f} GB")

# GPU node configuration
GPU_NODE_ADDRESS = "192.168.1.100:50051"  # Replace with your Windows laptop's IP and gRPC port

def try_gpu_forward(input_ids, attention_mask, position_ids):
    try:
        channel = grpc.insecure_channel(GPU_NODE_ADDRESS)
        stub = llm_pb2_grpc.LLMServiceStub(channel)
        request = llm_pb2.ForwardRequest(
            input_ids=input_ids[0].tolist(),
            attention_mask=attention_mask[0].tolist(),
            position_ids=position_ids[0].tolist()
        )
        response = stub.Forward(request, timeout=30)
        if response.activations:
            return torch.tensor(response.activations).reshape(input_ids.shape[0], -1)
        else:
            print("GPU node returned no activations.")
            return None
    except Exception as e:
        print(f"Error contacting GPU node: {e}")
        return None

@app.route('/generate', methods=['POST'])
def generate_cover_letter():
    def generate(user_message=None):
        if user_message:
            prompt = f"[INST] {user_message.strip()} [/INST]"
            inputs = tokenizer(prompt, return_tensors="pt")
            input_ids = inputs['input_ids']
            attention_mask = inputs['attention_mask']
            position_ids = torch.arange(input_ids.shape[1]).unsqueeze(0)

            # Try GPU node first
            gpu_activations = try_gpu_forward(input_ids, attention_mask, position_ids)
            if gpu_activations is not None:
                # (Optional) Continue processing on CPU node if doing model parallelism
                # For now, just return a placeholder response
                result = "[Response generated by GPU node]"
            else:
                # Fallback to local inference
                with torch.no_grad():
                    outputs = model.generate(
                        input_ids=input_ids,
                        attention_mask=attention_mask,
                        max_new_tokens=200,
                        do_sample=True,
                        temperature=0.8,
                        top_p=0.95,
                        top_k=40,
                        repetition_penalty=1.2
                    )
                    result = tokenizer.decode(outputs[0], skip_special_tokens=True)

            for word in result.split():
                yield f"data: {word} \n\n"
                time.sleep(0.05)
        yield "data: \n\n"

    if request.method == 'POST':
        data = request.get_json()
        user_message = data.get('job_description', '') if data else ''
        return Response(generate(user_message), mimetype='text/event-stream')

@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({"status": "healthy"}), 200

@app.route('/unload_model', methods=['POST'])
def unload_model():
    global model, tokenizer
    model = None
    tokenizer = None
    gc.collect()
    print("Model and tokenizer unloaded from memory.")
    return jsonify({"status": "unloaded"}), 200

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=8080)