# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\"\x87\x01\n\x0e\x46orwardRequest\x12\x13\n\x0b\x61\x63tivations\x18\x01 \x03(\x02\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\x0f\n\x07seq_len\x18\x03 \x01(\x05\x12\x12\n\nhidden_dim\x18\x04 \x01(\x05\x12\x16\n\x0e\x61ttention_mask\x18\x05 \x03(\x05\x12\x14\n\x0cposition_ids\x18\x06 \x03(\x05\"f\n\x0f\x46orwardResponse\x12\x0e\n\x06logits\x18\x01 \x03(\x02\x12\r\n\x05\x62\x61tch\x18\x02 \x01(\x05\x12\x0f\n\x07seq_len\x18\x03 \x01(\x05\x12\x12\n\nvocab_size\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\nLLMService\x12,\n\x07\x46orward\x12\x0f.ForwardRequest\x1a\x10.ForwardResponse\x12.\n\x0bHealthCheck\x12\x0e.HealthRequest\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDREQUEST']._serialized_start=14
  _globals['_FORWARDREQUEST']._serialized_end=149
  _globals['_FORWARDRESPONSE']._serialized_start=151
  _globals['_FORWARDRESPONSE']._serialized_end=253
  _globals['_HEALTHREQUEST']._serialized_start=255
  _globals['_HEALTHREQUEST']._serialized_end=270
  _globals['_HEALTHRESPONSE']._serialized_start=272
  _globals['_HEALTHRESPONSE']._serialized_end=304
  _globals['_LLMSERVICE']._serialized_start=306
  _globals['_LLMSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
