# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\";\n\x0e\x46orwardRequest\x12\x11\n\tinput_ids\x18\x01 \x03(\x05\x12\x16\n\x0e\x61ttention_mask\x18\x02 \x03(\x05\"9\n\x0f\x46orwardResponse\x12\x15\n\rgenerated_ids\x18\x01 \x03(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2j\n\nLLMService\x12,\n\x07\x46orward\x12\x0f.ForwardRequest\x1a\x10.ForwardResponse\x12.\n\x0bHealthCheck\x12\x0e.HealthRequest\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDREQUEST']._serialized_start=13
  _globals['_FORWARDREQUEST']._serialized_end=72
  _globals['_FORWARDRESPONSE']._serialized_start=74
  _globals['_FORWARDRESPONSE']._serialized_end=131
  _globals['_HEALTHREQUEST']._serialized_start=133
  _globals['_HEALTHREQUEST']._serialized_end=148
  _globals['_HEALTHRESPONSE']._serialized_start=150
  _globals['_HEALTHRESPONSE']._serialized_end=182
  _globals['_LLMSERVICE']._serialized_start=184
  _globals['_LLMSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
